on: [push]

jobs:
  ssm_test:
    runs-on: ubuntu-latest
    name: SSM Test
    env:
      K8S_Version: '1.21'
    steps:
      - name: Get SSM parameter value
        id: getparameter
        uses: mycloudtutorials/aws-ssm-get-parameter-action@v0.2
        with:
          aws-region: us-west-2
          parameter-name: "/aws/ssm/paramrter/ami-id/${{ env.K8S_Version }}/test"
      - name: Get the Output line
        run: echo "OUTPUT ${{ steps.getparameter.outputs.value }}"